name: outils_app
description: A Flutter app for managing products and cart with CRUD operations
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Notifications
  flutter_local_notifications: ^17.2.0

  # State Management
  provider: ^6.1.2

  # Navigation
  go_router: ^14.1.1

  # Local Storage
  shared_preferences: ^2.2.3
  path_provider: ^2.1.4
  sqflite: ^2.3.3
  sqflite_common_ffi: ^2.3.3

  # UI & Icons
  flutter_svg: ^2.0.10+1
  cupertino_icons: ^1.0.6

  # HTTP
  http: ^1.2.1
  mailer: ^6.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/products.json