# Mémoire & encodage (AGP 8 + JDK 17)
org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=1G -Dfile.encoding=UTF-8

# AndroidX obligatoire pour Flutter
android.useAndroidX=true
android.enableJetifier=true

# Kotlin 1.9.x – réglages sûrs
kotlin.code.style=official
kotlin.incremental=true
kotlin.jvm.target.validation.mode=warning

# Performances Gradle (facultatif mais utile)
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.configuration-cache=false
